### PR TITLE
feat: expose service_endpoints

### PR DESCRIPTION
**Pull request by kierramarie**
### Description
Service endpoint is needed to attach a private secret manager. This update exposes it. The default is public.

Related Issue: https://github.com/terraform-ibm-modules/terraform-ibm-secrets-manager-secret-group/issues/148

### Release required?

- [ ] No release
- [ ] Patch release (`x.x.X`)
- [ ] Minor release (`x.X.x`)
- [ ] Major release (`X.x.x`)

### Run the pipeline

If the CI pipeline doesn't run when you create the PR, the PR requires a user with GitHub collaborators access to run the pipeline.

Run the CI pipeline when the PR is ready for review and you expect tests to pass. Add a comment to the PR with the following text:

```
/run pipeline
```

### Checklist for reviewers

- [ ] If relevant, a test for the change is included or updated with this PR.
- [ ] If relevant, documentation for the change is included or updated with this PR.

### For mergers

- Use a conventional commit message to set the release level. Follow the [guidelines](https://terraform-ibm-modules.github.io/documentation/#/merging.md).
- Include information that users need to know about the PR in the commit message. The commit message becomes part of the GitHub release notes.
- Use the **Squash and merge** option.

### CODE REVIEW

**Comment by kierramarie** [comment]
Upgrade test failed because the endpoint_type changes from null to public. Running this on my own it appears that nothing is destroyed, but only updated in place. So this change shouldn't cause issues for users.
```Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the
following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # module.secrets_manager_group_acct.ibm_sm_secret_group.secret_group will be updated in-place
  ~ resource "ibm_sm_secret_group" "secret_group" {
      + endpoint_type   = "public"
        id              = "us-south/118fdb09-7551-4232-be12-0f5cca4c188b/dd8e034a-63b4-0099-cd46-fec7738b63c3"
        name            = "test-sm-sg-module-example-group"
        # (6 unchanged attributes hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.```

**Comment by ocofaigh** [comment]
Approve for upgrade test to be skipped

**Review by ocofaigh — APPROVED** [review]

**Pull request merged**
